### PR TITLE
Updated GSAP to 1.11.5

### PR DESCRIPTION
**Pull request by brentjanderson**
Using unminified sources in a git submodule to make it easier to update and debug.

### CODE REVIEW

**Comment by RoyalMist** [comment]
Thanks for your contribution Brent :)

**Comment by brentjanderson** [comment]
Any chance we can publish this to Meteorite now?

**Comment by RoyalMist** [comment]
Yep I will after my work :). I live in France so it should be in your afternoon :)

---

Cordialement,

Thibault Fouache

**Comment by RoyalMist** [comment]
Pushed to atmosphere :)

**Comment by RoyalMist** [comment]
In fact vendor is empty when adding package to a meteor app.

Never worked with git submodules any tips ?

**Comment by brentjanderson** [comment]
I just added it and it worked out no problem. Did you try mrt update?

**Comment by RoyalMist** [comment]
You add gsap package to your project and it's ok ?

Got this, like if I cannot retrieve the sumodule :( ?

PrisM:src PrisM$ mrt add gsap
smart.json changed.. installing from smart.json
✓ iron-router
    tag: https://github.com/EventedMind/iron-router.git#v0.6.4
✓ bootstrap-3
    tag: https://github.com/mangasocial/meteor-bootstrap-3.git#v3.1.1-1
✓ roles
    tag: https://github.com/alanning/meteor-roles.git#v1.2.6
✓ spin
    tag: https://github.com/SachaG/meteor-spin.git#v0.2.2
✓ npm
    tag: https://github.com/arunoda/meteor-npm.git#v0.2.6
✓ gsap
    tag: https://github.com/RoyalMist/meteor-gsap.git#v1.11.5

Done installing smart packages

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

=> Errors while scanning packages:

While building package `gsap`:
error: File not found: vendor/GreenSock-JS/src/uncompressed/easing/EasePack.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/AttrPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/BezierPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/ColorPropsPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/CSSPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/CSSRulePlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/DirectionalRotationPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/EaselPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/KineticPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/RaphaelPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/RoundPropsPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/ScrollToPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/TextPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/jquery.gsap.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TimelineLite.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TimelineMax.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TweenLite.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TweenMax.js
PrisM:src PrisM$

**Comment by brentjanderson** [comment]
I did the following:

mrt create temp
cd temp
mrt add gsap
mrt

Not sure about your individual project

**Comment by RoyalMist** [comment]
Seems like I got a local git problem :

PrisM:Atmosphere PrisM$ mrt create temp
temp: created.

To run your new app:
   cd temp
   meteor
PrisM:Atmosphere PrisM$ cd temp
PrisM:temp PrisM$ mrt add gsap
✓ gsap
    tag: https://github.com/RoyalMist/meteor-gsap.git#v1.11.5

Done installing smart packages

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

=> Errors while scanning packages:

While building package `gsap`:
error: File not found: vendor/GreenSock-JS/src/uncompressed/easing/EasePack.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/AttrPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/BezierPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/ColorPropsPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/CSSPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/CSSRulePlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/DirectionalRotationPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/EaselPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/KineticPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/RaphaelPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/RoundPropsPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/ScrollToPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/plugins/TextPlugin.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/jquery.gsap.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TimelineLite.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TimelineMax.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TweenLite.js
error: File not found: vendor/GreenSock-JS/src/uncompressed/TweenMax.js

**Comment by RoyalMist** [comment]
Got it when I update the project :

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:greensock/GreenSock-JS.git' into submodule path 'vendor/GreenSock-JS' failed
Cloning into 'vendor/GreenSock-JS'...
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by brentjanderson** [comment]
Ah - it’s the submodule definition. I use SSH for my modules, didn’t realize that would break even if it’s public. I can switch it to HTTPS and it should work just fine.

**Comment by RoyalMist** [comment]
I wiil try this one :

url = git@github.com:greensock/GreenSock-JS.git --> url = git//github.com/greensock/GreenSock-JS.git :)

**Comment by RoyalMist** [comment]
Now I can update correctly my project but the package still not working on meteor... (for me)

**Comment by RoyalMist** [comment]
Is it working for you ?

Still not for me with meteor. But ok with git.

I will retest that tomorrow.

**Comment by brentjanderson** [comment]
Seems to work great.

I’m using the following versions:

Meteorite version 0.7.2
Meteor Release 0.7.1.2
git version 1.8.5.2 (Apple Git-48)

**Comment by RoyalMist** [comment]
Ok cool I will just have a look at my meteorite version.

---

Cordialement,

Thibault Fouache

**Pull request merged**
